/**
 * @file tel2000_param.h
 * Tel2000 axi port address map.
 *
 * This file declares the address of every axi lite port.
 * This is automaticly generated by tel_extract_param.tcl
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2014 Telops Inc.
 */
 
#ifndef TEL2000_PARAM_H
#define TEL2000_PARAM_H
 
 /**
 * AXI PORT declaration
 */
/* Definitions for peripheral TEL_AXIL_CLINK */
#define TEL_PAR_TEL_AXIL_CLINK_BASEADDR 0x44A00000
#define TEL_PAR_TEL_AXIL_CLINK_HIGHADDR 0x44A00FFF 

/* Definitions for peripheral TEL_AXIL_FAN_CTRL */
#define TEL_PAR_TEL_AXIL_FAN_CTRL_BASEADDR 0x44A10000
#define TEL_PAR_TEL_AXIL_FAN_CTRL_HIGHADDR 0x44A10FFF 

/* Definitions for peripheral TEL_AXIL_FB_CTRL */
#define TEL_PAR_TEL_AXIL_FB_CTRL_BASEADDR 0x44A40000
#define TEL_PAR_TEL_AXIL_FB_CTRL_HIGHADDR 0x44A4FFFF 

/* Definitions for peripheral TEL_AXIL_PLEORA_CTRL */
#define TEL_PAR_TEL_AXIL_PLEORA_CTRL_BASEADDR 0x44A50000
#define TEL_PAR_TEL_AXIL_PLEORA_CTRL_HIGHADDR 0x44A5FFFF 

/* Definitions for peripheral TEL_AXIL_SDI_CTRL */
#define TEL_PAR_TEL_AXIL_SDI_CTRL_BASEADDR 0x44A80000
#define TEL_PAR_TEL_AXIL_SDI_CTRL_HIGHADDR 0x44ABFFFF 

#endif // TEL2000_PARAM_H
