/**
 * @file tel2000_param.h
 * Tel2000 axi port address map.
 *
 * This file declares the address of every axi lite port.
 * This is automaticly generated by tel_extract_param.tcl
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2014 Telops Inc.
 */
 
#ifndef TEL2000_PARAM_H
#define TEL2000_PARAM_H
 
 /**
* Clock declaration
*/
#define CLK_50_FREQ_HZ 50000000
#define CLK_CORE_SCALER_FREQ_HZ 210000000
#define CLK_DATA_FREQ_HZ 85000000
#define CLK_DATA_N_FREQ_HZ 85000000
#define CLK_MB_FREQ_HZ 100000000

#endif // TEL2000_PARAM_H
