/**
 * @file tel2000_param.h
 * Tel2000 axi port address map.
 *
 * This file declares the address of every axi lite port.
 * This is automaticly generated by tel_extract_param.tcl
 *
 * $Rev$
 * $Author$
 * $Date$
 * $Id$
 * $URL$
 *
 * (c) Copyright 2014 Telops Inc.
 */
 
#ifndef TEL2000_PARAM_H
#define TEL2000_PARAM_H
 
 /**
* Clock declaration
*/
#define CLK_50_FREQ_HZ 50000000
#define CLK_CORE_SCALER_FREQ_HZ 170000000
#define CLK_DATA_FREQ_HZ 85000000
#define CLK_DATA_N_FREQ_HZ 85000000
#define CLK_MB_FREQ_HZ 100000000

/**
 * AXI PORT declaration
 */
/* Definitions for peripheral TEL_AXIL_CLINK */
#define TEL_PAR_TEL_AXIL_CLINK_BASEADDR 0x00160000
#define TEL_PAR_TEL_AXIL_CLINK_HIGHADDR 0x0016FFFF 

/* Definitions for peripheral TEL_AXIL_FAN_CTRL */
#define TEL_PAR_TEL_AXIL_FAN_CTRL_BASEADDR 0x00170000
#define TEL_PAR_TEL_AXIL_FAN_CTRL_HIGHADDR 0x0017FFFF 

/* Definitions for peripheral TEL_AXIL_FB_CTRL */
#define TEL_PAR_TEL_AXIL_FB_CTRL_BASEADDR 0x00180000
#define TEL_PAR_TEL_AXIL_FB_CTRL_HIGHADDR 0x0018FFFF 

/* Definitions for peripheral TEL_AXIL_PLEORA_CTRL */
#define TEL_PAR_TEL_AXIL_PLEORA_CTRL_BASEADDR 0x001A0000
#define TEL_PAR_TEL_AXIL_PLEORA_CTRL_HIGHADDR 0x001AFFFF 

/* Definitions for peripheral TEL_AXIL_SDI_CTRL */
#define TEL_PAR_TEL_AXIL_SDI_CTRL_BASEADDR 0x001B0000
#define TEL_PAR_TEL_AXIL_SDI_CTRL_HIGHADDR 0x001BFFFF 

#endif // TEL2000_PARAM_H
